apiVersion: v1   

kind: Pod

metadata:
  name: my-pod   
  labels:        
    app: myapp
    owner: me
    contact: me@gmail.com

spec:
  containers:    
    - name: nginx-container
      image: nginx:1.14.2
      ports:
      - containerPort: 80